<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Modules\Products\Infrastructure\Persistence\Models\Producto;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'slug' => 'colageno-hidrolizado-vitaella',
                'nombre' => 'Colágeno Hidrolizado Original',
                'categoria' => 'colageno',
                'descripcion' => 'Fórmula clásica en polvo con vitamina C para piel firme y cabello fuerte desde la primera caja.',
                'long_description' => 'Nuestra fórmula insignia combina colágeno hidrolizado de bajo peso molecular con vitamina C para potenciar su absorción y estimular tu producción natural. Sin sabor artificial, se disuelve por completo en segundos y se integra fácil a tu rutina diaria.',
                'precio' => 109.90,
                'precio_anterior' => 0.00,
                'rating' => 5.0,
                'reviews' => 482,
                'badge' => 'Bestseller',
                'destacado' => true,
                'presentacion' => '30 sobres x 10 g',
                'modo_de_uso' => 'Disuelve un sobre en un vaso de agua, jugo o yogurt. Tómalo preferentemente en ayunas, todos los días.',
                'caracteristicas' => ['Colágeno tipo I y III', 'Vitamina C', 'Biotina', 'Ácido hialurónico'],
                'beneficios' => [
                    ['title' => 'Piel más firme', 'description' => 'Mejora la elasticidad e hidratación, reduciendo líneas de expresión.'],
                    ['title' => 'Cabello más fuerte', 'description' => 'Aporta aminoácidos clave para un cabello con más brillo y densidad.'],
                    ['title' => 'Articulaciones sanas', 'description' => 'Favorece la movilidad, ideal para quienes se mantienen activas.'],
                ],
                'imagen' => 'https://ezzetacompany.com/wp-content/uploads/2026/07/Gemini_Generated_Image_xmo2xsxmo2xsxmo2.png',
                'stock' => 50,
                'activo' => true,
            ],
            [
                'slug' => 'colageno-biotina-capilar',
                'nombre' => 'Colágeno + Biotina Capilar',
                'categoria' => 'colageno',
                'descripcion' => 'Potenciado con biotina y zinc para frenar la caída y dar brillo intenso al cabello.',
                'long_description' => 'Diseñado especialmente para quienes buscan fortalecer su cabello desde la raíz. La combinación de colágeno, biotina y zinc nutre el folículo capilar, reduce la caída visible y devuelve el brillo natural en pocas semanas de uso constante.',
                'precio' => 94.90,
                'precio_anterior' => 0.00,
                'rating' => 5.0,
                'reviews' => 216,
                'badge' => 'Oferta',
                'destacado' => true,
                'presentacion' => '30 sobres x 10 g',
                'modo_de_uso' => 'Mezcla un sobre con agua fría o tibia una vez al día, junto a una comida principal.',
                'caracteristicas' => ['Biotina', 'Zinc', 'Colágeno hidrolizado', 'Vitamina E'],
                'beneficios' => [
                    ['title' => 'Menos caída', 'description' => 'Fortalece el folículo capilar y reduce la caída visible del cabello.'],
                    ['title' => 'Más brillo', 'description' => 'Nutre la fibra capilar devolviendo luminosidad y suavidad.'],
                    ['title' => 'Uñas resistentes', 'description' => 'La biotina también fortalece uñas débiles y quebradizas.'],
                ],
                'stock' => 30,
                'activo' => true,
            ],
            [
                'slug' => 'colageno-marino-antiedad',
                'nombre' => 'Colágeno Marino Antiedad',
                'categoria' => 'colageno',
                'descripcion' => 'Péptidos marinos de bajo peso molecular para una piel más tersa y luminosa.',
                'long_description' => 'Extraído de fuentes marinas sostenibles, este colágeno de bajo peso molecular se absorbe hasta 1.5 veces más rápido que el colágeno bovino tradicional. Combinado con antioxidantes, ayuda a combatir los signos visibles del envejecimiento.',
                'precio' => 99.90,
                'precio_anterior' => 0.00,
                'rating' => 4.0,
                'reviews' => 87,
                'badge' => 'Nuevo',
                'destacado' => true,
                'presentacion' => '30 sobres x 8 g',
                'modo_de_uso' => 'Disuelve un sobre en medio vaso de agua fría. Tómalo por la noche antes de dormir.',
                'caracteristicas' => ['Colágeno marino', 'Coenzima Q10', 'Vitamina E', 'Resveratrol'],
                'beneficios' => [
                    ['title' => 'Piel más tersa', 'description' => 'Reduce la profundidad de arrugas y mejora la firmeza facial.'],
                    ['title' => 'Efecto antioxidante', 'description' => 'Protege la piel del daño causado por radicales libres.'],
                    ['title' => 'Absorción rápida', 'description' => 'Péptidos de bajo peso molecular para mejor biodisponibilidad.'],
                ],
                'stock' => 25,
                'activo' => true,
            ],
            [
                'slug' => 'multivitaminico-mujer-balance',
                'nombre' => 'Multivitamínico Mujer Balance',
                'categoria' => 'vitaminas',
                'descripcion' => 'Mezcla de 12 vitaminas y minerales pensada para energía diaria y equilibrio hormonal.',
                'long_description' => 'Formulado con 12 vitaminas y minerales esenciales, este multivitamínico está pensado para acompañar el ritmo de vida activo de la mujer moderna, apoyando la energía diaria, el equilibrio hormonal y las defensas.',
                'precio' => 59.90,
                'precio_anterior' => 0.00,
                'rating' => 5.0,
                'reviews' => 340,
                'badge' => null,
                'destacado' => false,
                'presentacion' => '60 cápsulas',
                'modo_de_uso' => 'Toma una cápsula al día junto con alimentos, preferentemente en el desayuno.',
                'caracteristicas' => ['Vitaminas B6, B12 y D3', 'Hierro', 'Ácido fólico', 'Zinc'],
                'beneficios' => [
                    ['title' => 'Energía sostenida', 'description' => 'El complejo B ayuda a convertir los alimentos en energía real.'],
                    ['title' => 'Equilibrio hormonal', 'description' => 'Apoya la regulación hormonal durante todo el mes.'],
                    ['title' => 'Defensas fuertes', 'description' => 'Zinc y vitamina D3 refuerzan tu sistema inmune.'],
                ],
                'stock' => 40,
                'activo' => true,
            ],
            [
                'slug' => 'magnesio-bisglicinato-relax',
                'nombre' => 'Magnesio Bisglicinato Relax',
                'categoria' => 'vitaminas',
                'descripcion' => 'Alta absorción para relajación muscular, mejor descanso y menos fatiga.',
                'long_description' => 'El magnesio bisglicinato es una de las formas mejor toleradas y absorbidas de este mineral. Ayuda a relajar la musculatura, mejorar la calidad del sueño y reducir la sensación de fatiga acumulada del día a día.',
                'precio' => 49.90,
                'precio_anterior' => 0.00,
                'rating' => 4.0,
                'reviews' => 158,
                'badge' => null,
                'destacado' => false,
                'presentacion' => '60 cápsulas',
                'modo_de_uso' => 'Toma 2 cápsulas por la noche, media hora antes de dormir.',
                'caracteristicas' => ['Magnesio bisglicinato', 'Vitamina B6', 'Sin laxante', 'Alta absorción'],
                'beneficios' => [
                    ['title' => 'Mejor descanso', 'description' => 'Favorece la relajación muscular y un sueño más profundo.'],
                    ['title' => 'Menos fatiga', 'description' => 'Participa en más de 300 procesos energéticos del cuerpo.'],
                    ['title' => 'Calma muscular', 'description' => 'Reduce calambres y tensión acumulada tras el ejercicio.'],
                ],
                'stock' => 35,
                'activo' => true,
            ],
            [
                'slug' => 'omega-3-ultra-pure',
                'nombre' => 'Omega 3 Ultra Pure',
                'categoria' => 'vitaminas',
                'descripcion' => 'Aceite de pescado purificado, alto en EPA/DHA para corazón y mente en forma.',
                'long_description' => 'Cápsulas de aceite de pescado de triple destilación, con altas concentraciones de EPA y DHA. Libre de metales pesados y sin sabor a pescado, ideal para cuidar tu salud cardiovascular y cognitiva a diario.',
                'precio' => 64.90,
                'precio_anterior' => 0.00,
                'rating' => 5.0,
                'reviews' => 201,
                'badge' => 'Oferta',
                'destacado' => true,
                'presentacion' => '60 cápsulas blandas',
                'modo_de_uso' => 'Toma 2 cápsulas al día junto con una comida que contenga grasas para mejor absorción.',
                'caracteristicas' => ['EPA y DHA', 'Triple destilación', 'Sin sabor a pescado', 'Libre de metales pesados'],
                'beneficios' => [
                    ['title' => 'Corazón sano', 'description' => 'Ayuda a mantener niveles saludables de triglicéridos.'],
                    ['title' => 'Mente enfocada', 'description' => 'El DHA apoya la función cognitiva y la memoria.'],
                    ['title' => 'Piel hidratada', 'description' => 'Los ácidos grasos esenciales nutren la piel desde adentro.'],
                ],
                'stock' => 20,
                'activo' => true,
            ],
            [
                'slug' => 'serum-hialuronico-vitc',
                'nombre' => 'Sérum Ácido Hialurónico + Vit. C',
                'categoria' => 'skincare',
                'descripcion' => 'Hidratación profunda y luminosidad inmediata en una fórmula ligera de rápida absorción.',
                'long_description' => 'Un sérum ligero de textura gel que combina ácido hialurónico de tres pesos moleculares con vitamina C estabilizada. Hidrata en profundidad, ilumina el tono de la piel y ayuda a prevenir signos de envejecimiento prematuro.',
                'precio' => 79.90,
                'precio_anterior' => 0.00,
                'rating' => 5.0,
                'reviews' => 129,
                'badge' => 'Nuevo',
                'destacado' => true,
                'presentacion' => 'Frasco 30 ml',
                'modo_de_uso' => 'Aplica 3-4 gotas sobre rostro limpio, mañana y noche, antes de tu crema hidratante.',
                'caracteristicas' => ['Ácido hialurónico', 'Vitamina C estabilizada', 'Sin fragancia', 'Apto piel sensible'],
                'beneficios' => [
                    ['title' => 'Hidratación profunda', 'description' => 'Retiene la humedad en múltiples capas de la piel.'],
                    ['title' => 'Piel luminosa', 'description' => 'La vitamina C unifica el tono y aporta luminosidad.'],
                    ['title' => 'Textura ligera', 'description' => 'Absorción rápida sin dejar sensación grasosa.'],
                ],
                'stock' => 15,
                'activo' => true,
            ],
            [
                'slug' => 'crema-facial-durazno',
                'nombre' => 'Crema Facial Nutritiva Durazno',
                'categoria' => 'skincare',
                'descripcion' => 'Textura en mousse con extracto de durazno que nutre sin dejar sensación grasosa.',
                'long_description' => 'Una crema facial de textura mousse, ligera y de rápida absorción, formulada con extracto de durazno y manteca de karité. Nutre profundamente, suaviza la piel y deja un aroma fresco y delicado durante todo el día.',
                'precio' => 69.90,
                'precio_anterior' => 0.00,
                'rating' => 4.0,
                'reviews' => 96,
                'badge' => null,
                'destacado' => false,
                'presentacion' => 'Frasco 50 ml',
                'modo_de_uso' => 'Aplica sobre rostro y cuello limpios con movimientos circulares, mañana y noche.',
                'caracteristicas' => ['Extracto de durazno', 'Manteca de karité', 'Vitamina E', 'Libre de parabenos'],
                'beneficios' => [
                    ['title' => 'Nutrición profunda', 'description' => 'Repone la barrera de hidratación natural de la piel.'],
                    ['title' => 'Piel suave', 'description' => 'Textura mousse que se absorbe sin dejar residuo graso.'],
                    ['title' => 'Aroma delicado', 'description' => 'Fragancia natural a durazno, suave y duradera.'],
                ],
                'stock' => 18,
                'activo' => true,
            ],
            [
                'slug' => 'te-detox-herbal',
                'nombre' => 'Té Detox Herbal Vitaella',
                'categoria' => 'bienestar',
                'descripcion' => 'Blend de hierbas naturales que acompaña la digestión y reduce la hinchazón.',
                'long_description' => 'Un blend artesanal de hierbas seleccionadas —diente de león, jengibre y menta— que acompaña de forma natural los procesos digestivos y ayuda a reducir la sensación de hinchazón después de las comidas.',
                'precio' => 34.90,
                'precio_anterior' => 0.00,
                'rating' => 4.0,
                'reviews' => 174,
                'badge' => null,
                'destacado' => false,
                'presentacion' => '20 bolsitas de infusión',
                'modo_de_uso' => 'Vierte agua caliente sobre una bolsita y deja reposar 5 minutos. Toma después de tus comidas principales.',
                'caracteristicas' => ['Diente de león', 'Jengibre', 'Menta', 'Sin cafeína'],
                'beneficios' => [
                    ['title' => 'Mejor digestión', 'description' => 'Las hierbas naturales acompañan el proceso digestivo diario.'],
                    ['title' => 'Menos hinchazón', 'description' => 'Ayuda a aliviar la sensación de pesadez después de comer.'],
                    ['title' => 'Relajante', 'description' => 'Ideal como ritual de pausa en cualquier momento del día.'],
                ],
                'stock' => 45,
                'activo' => true,
            ],
            [
                'slug' => 'probioticos-flora-balance',
                'nombre' => 'Probióticos Flora Balance',
                'categoria' => 'bienestar',
                'descripcion' => '10 cepas vivas para una digestión saludable y un sistema inmune más fuerte.',
                'long_description' => 'Una fórmula con 10 cepas probióticas vivas y 20 mil millones de UFC por cápsula, con recubrimiento entérico que protege a las bacterias del ácido estomacal para que lleguen activas al intestino.',
                'precio' => 54.90,
                'precio_anterior' => 0.00,
                'rating' => 5.0,
                'reviews' => 263,
                'badge' => 'Bestseller',
                'destacado' => true,
                'presentacion' => '30 cápsulas',
                'modo_de_uso' => 'Toma una cápsula al día, preferentemente en ayunas con un vaso de agua.',
                'caracteristicas' => ['10 cepas vivas', '20 mil millones UFC', 'Recubrimiento entérico', 'No requiere refrigeración'],
                'beneficios' => [
                    ['title' => 'Digestión saludable', 'description' => 'Equilibra la flora intestinal y mejora la digestión.'],
                    ['title' => 'Inmunidad fuerte', 'description' => 'Gran parte del sistema inmune vive en el intestino.'],
                    ['title' => 'Menos hinchazón', 'description' => 'Ayuda a reducir gases y molestias digestivas.'],
                ],
                'stock' => 30,
                'activo' => true,
            ],
        ];

        foreach ($products as $product) {
            Producto::query()->updateOrCreate(
                ['slug' => $product['slug']],
                $product
            );
        }
    }
}
